services:
  - type: web
    name: jobboard
    env: docker
    plan: free
    branch: main
    buildCommand: ""  # Dockerfile handles everything
    startCommand: ""  # CMD in Dockerfile is used
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:2+U5bpZ/EP8l8roiw9q1NWy8oSmm23sqtayfDfOT2nw=
      - key: APP_URL
        value: https://jobboard-ghey.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: SESSION_SAME_SITE
        value: none
